### ISSUE TITLE
can support unorder list

### ISSUE THREAD

**Issue by Kurt-Shiwz** [WiseGuru/obsidian-automatic-list-styles#2]
can support unorder list with "disc","circle","square". like this
![image](https://github.com/WiseGuru/obsidian-automatic-list-styles/assets/7554917/d510662e-5c7e-4441-98f4-05addeacdd31)

**Comment by WiseGuru** [comment]
That's a good idea; I'll take a look and see what I can do.

**Comment by WiseGuru** [comment]
So I've been toying with it, and I discovered a problem. The themes are butting heads with the unordered list formatting. See below; at first, I thought it was just formatting the "circle" style strangely, but when I zoomed in, I saw that it was actually show both a bullet AND whatever formatted list type I set.

![image](https://github.com/WiseGuru/obsidian-automatic-list-styles/assets/42100212/19339730-d151-4c94-8aa5-582a033cf645)

It's probably something hard-coded into Obsidian since if I apply the 80s Neon theme, you can see the conflict of list styles even more clearly (there are three overlapping list styles for unordered lists!).

![image](https://github.com/WiseGuru/obsidian-automatic-list-styles/assets/42100212/af3cab74-3350-47f8-ac66-e1317b68eb6d)

With this in mind, I don't think I want to integrate the changes into the plugin since it will probably break working configurations.

If you would like to do it yourself, I would be happy to share the script with you to manually add it to your own vaults, or so you can fork my repo and publish it yourself.

**Comment by WiseGuru** [comment]
FYI, I added the code as a branch to this repo; please take it and run with it!

If you want to try it without any coding, you can just download the "main.js" and the "manifest.json" file from the branch (https://github.com/WiseGuru/obsidian-automatic-list-styles/tree/2-can-support-unorder-list), paste them into the automatic list plugin folder and overwrite current files (C:\Path\to\vault\.obsidian\plugins\automatic-list-styles), and you'll be set!

**Comment by WiseGuru** [comment]
Oops, closed as completed; should be marked as unplanned.
